# Generated by Django 6.0.2 on 2026-02-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquerylog',
            name='image_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
