# Generated by Django 6.0.2 on 2026-02-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_aiquerylog_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquerylog',
            name='map_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
