# Generated by Django 6.0.2 on 2026-02-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('training', 'Training'), ('trained', 'Trained'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('model_type', models.CharField(default='YOLOv8', max_length=100)),
                ('total_videos', models.IntegerField(default=0)),
                ('total_frames', models.IntegerField(default=0)),
                ('train_split', models.FloatField(default=0.8)),
                ('test_split', models.FloatField(default=0.2)),
                ('accuracy', models.FloatField(default=0)),
                ('precision_val', models.FloatField(default=0)),
                ('recall_val', models.FloatField(default=0)),
                ('f1_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='ai_training.trainingjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='training_videos/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration', models.FloatField(default=0, help_text='Duration in seconds')),
                ('frame_count', models.IntegerField(default=0)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ai_training.trainingdataset')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('result_json', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0)),
                ('processing_time', models.FloatField(default=0, help_text='Time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='ai_training.trainingdataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
